# Kodosumi v0.9.2 configuration for Political Monitoring Agent

# Server configuration
proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8001
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
  additional_log_standard_attrs: []

# Kodosumi application deployment
applications:
  - name: political-monitoring-agent
    route_prefix: /political-analysis
    import_path: app:fast_app
    runtime_env:
      working_dir: .
      pip:
        # Kodosumi Framework
        - kodosumi==0.9.2
        # Core Framework
        - ray[serve]==2.46.0
        - fastapi==0.104.1
        - uvicorn==0.24.0
        - python-multipart==0.0.6
        # Workflow & State Management
        - langgraph==0.2.3
        - pydantic>=2.7.4,<3.0.0
        - pydantic-settings>=2.3.0,<3.0.0
        # Document Processing
        - pypdf2==3.0.1
        - python-docx==1.1.0
        - markdown==3.5.1
        - beautifulsoup4==4.12.2
        - lxml==4.9.3
        # AI/ML Components
        - numpy==1.26.2
        - scikit-learn==1.3.2
        - tiktoken>=0.7,<1
        # LLM Integration
        - langchain==0.2.16
        - langchain-openai==0.1.25
        - langchain-anthropic==0.1.23
        - langchain-community==0.2.16
        - langfuse==2.36.1
        # Output Generation
        - jinja2==3.1.2
        - tabulate==0.9.0
        # Utilities
        - python-dotenv==1.0.0
        - pyyaml==6.0.1
        - aiofiles==23.2.1
        - httpx==0.25.2
        # Monitoring & Logging
        - structlog==23.2.0
        - prometheus-client==0.19.0
        # Azure Storage
        - azure-storage-blob>=12.25.1
        - azure-identity>=1.23.0
      env_vars:
        PYTHONPATH: .
        LOG_LEVEL: INFO
        LOG_FORMAT: json
        RAY_ADDRESS: auto
        # Storage Configuration
        USE_AZURE_STORAGE: "true"
        AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
        # LLM Configuration
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
        # Langfuse Configuration
        LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
        LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
        LANGFUSE_HOST: ${LANGFUSE_HOST}
        # Application Settings
        DEFAULT_OUTPUT_FOLDER: /data/output
        DEFAULT_INPUT_FOLDER: /data/input
        DEFAULT_CONTEXT_FOLDER: /data/context
        MAX_BATCH_SIZE: 1000
        PROCESSING_TIMEOUT_SECONDS: 1800
        RAY_NUM_CPUS: 4
    ray_actor_options:
      num_cpus: 2
      memory: 4000000000  # 4GB
    autoscaling_config:
      min_replicas: 1
      max_replicas: 10
      target_num_ongoing_requests_per_replica: 2.0