proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8001
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
  additional_log_standard_attrs: []
applications:
- name: political-monitoring-agent
  route_prefix: /political-analysis
  import_path: src.app:fast_app
  runtime_env:
    env_vars:
      PYTHONPATH: .
      LOG_LEVEL: INFO
      LOG_FORMAT: json
      RAY_ADDRESS: auto
      USE_AZURE_STORAGE: 'false'
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;
      OPENAI_API_KEY: sk-your-openai-api-key-here
      ANTHROPIC_API_KEY: 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
      LANGFUSE_PUBLIC_KEY: pk-lf-7ce666a0-8a96-4b2f-8385-eb50ce2f44f5
      LANGFUSE_SECRET_KEY: sk-lf-65579bec-9f27-4fd0-877c-b52f2650b9b4
      LANGFUSE_HOST: http://localhost:3000
      DEFAULT_OUTPUT_FOLDER: ./data/output
      DEFAULT_INPUT_FOLDER: ./data/input
      DEFAULT_CONTEXT_FOLDER: ./data/context
      MAX_BATCH_SIZE: '1000'
      PROCESSING_TIMEOUT_SECONDS: '600'
      RAY_NUM_CPUS: '8'
      ENVIRONMENT: development
      AZURE_JOB_ID: import_20250524_231831
      AZURE_INPUT_PATH: jobs/import_20250524_231831/input
      AZURE_CONTEXT_PATH: test-client/context.yaml
      AZURE_OUTPUT_PATH: jobs/import_20250524_231831/output
      LLM_ENABLED: 'true'
      LLM_PROVIDER: anthropic
      OPENAI_MODEL: gpt-4
      OPENAI_MAX_TOKENS: '2000'
      OPENAI_TEMPERATURE: '0.1'
      ANTHROPIC_MODEL: claude-3-sonnet-20240229
      ANTHROPIC_MAX_TOKENS: '2000'
      ANTHROPIC_TEMPERATURE: '0.1'
      LLM_MAX_CONCURRENT: '3'
      LLM_TIMEOUT_SECONDS: '30'
      LLM_FALLBACK_ENABLED: 'true'
      MAX_DOCUMENT_SIZE_MB: '50'
      CONFIDENCE_THRESHOLD: '0.7'
      PRIORITY_THRESHOLD: '70.0'
      RAY_TASK_MAX_RETRIES: '3'
      RAY_TASK_TIMEOUT_SECONDS: '300'
      ENABLE_PERFORMANCE_LOGGING: 'true'
  ray_actor_options:
    num_cpus: 2
    memory: 4000000000
  autoscaling_config:
    min_replicas: 1
    max_replicas: 10
    target_num_ongoing_requests_per_replica: 2.0
