# Kodosumi v0.9.2 configuration for Political Monitoring Agent

# Server configuration
proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8001
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
  additional_log_standard_attrs: []

# Kodosumi application deployment
applications:
  - name: political-monitoring-agent
    route_prefix: /political-analysis
    import_path: app:fast_app
    runtime_env:
      env_vars:
        PYTHONPATH: .
        LOG_LEVEL: INFO
        LOG_FORMAT: json
        RAY_ADDRESS: auto
        # Storage Configuration
        USE_AZURE_STORAGE: "true"
        AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
        # LLM Configuration
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
        # Langfuse Configuration
        LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
        LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
        LANGFUSE_HOST: ${LANGFUSE_HOST}
        # Application Settings
        DEFAULT_OUTPUT_FOLDER: /data/output
        DEFAULT_INPUT_FOLDER: /data/input
        DEFAULT_CONTEXT_FOLDER: /data/context
        MAX_BATCH_SIZE: "1000"
        PROCESSING_TIMEOUT_SECONDS: "1800"
        RAY_NUM_CPUS: "4"
    ray_actor_options:
      num_cpus: 2
      memory: 4000000000  # 4GB
    autoscaling_config:
      min_replicas: 1
      max_replicas: 10
      target_num_ongoing_requests_per_replica: 2.0