services:
  # PostgreSQL database for Langfuse
  postgres:
    image: postgres:15-alpine
    container_name: policiytracker-postgres
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d langfuse"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Langfuse for LLM observability
  langfuse-server:
    image: langfuse/langfuse:2
    container_name: policiytracker-langfuse
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      # Database
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/langfuse
      DIRECT_URL: postgresql://postgres:postgres@postgres:5432/langfuse
      
      # Auth & Security
      NEXTAUTH_SECRET: changeme-nextauth-secret
      NEXTAUTH_URL: http://localhost:3001
      SALT: changeme-salt
      
      # Feature flags
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
    volumes:
      - langfuse_data:/app/.next
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Azurite - Azure Storage Emulator for local development
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: policiytracker-azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service  
      - "10002:10002"  # Table service
    volumes:
      - azurite_data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
  langfuse_data:
  azurite_data:

networks:
  default:
    name: policiytracker-network