"""System prompts for weekly report category agents."""

from .category_prompts import (
    COMPLIANCE_SYSTEM_PROMPT,
    EVENTS_SYSTEM_PROMPT,
    LEGISLATIVE_SYSTEM_PROMPT,
    PERSONNEL_SYSTEM_PROMPT,
    POLICY_SYSTEM_PROMPT,
    SYNTHESIZER_SYSTEM_PROMPT,
)

__all__ = [
    "LEGISLATIVE_SYSTEM_PROMPT",
    "PERSONNEL_SYSTEM_PROMPT",
    "COMPLIANCE_SYSTEM_PROMPT",
    "POLICY_SYSTEM_PROMPT",
    "EVENTS_SYSTEM_PROMPT",
    "SYNTHESIZER_SYSTEM_PROMPT",
]
